import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, Trophy, CalendarDays, Users, Star, Goal, Shield, RefreshCw } from 'lucide-react';
import api from '../../services/api';
const formatDate = value => new Date(value).toLocaleDateString('id-ID', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' });
function ClubMark({ team }) { return team?.logo ? <img className="club-mark" src={team.logo} alt="" /> : <span className="club-mark">{(team?.name || 'SF').slice(0, 2).toUpperCase()}</span>; }
function SectionHeading({ eyebrow, title, to, label }) { return <div className="home-section-heading"><div><span className="public-eyebrow">{eyebrow}</span><h2>{title}</h2></div><Link to={to}>{label} <ArrowUpRight size={17} /></Link></div>; }
export default function Home() {
  const [data, setData] = useState({ fixtures: [], standings: [], leaders: { top_scorers: [], top_rated: [] }, counts: null });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  function load() {
    return Promise.all([api.get('/fixtures'), api.get('/league-table'), api.get('/leaderboard'), api.get('/dashboard-stats')])
      .then(([fixtures, standings, leaders, counts]) => {
        setData({ fixtures: fixtures.data, standings: standings.data, leaders: leaders.data, counts: counts.data });
      })
      .catch(() => setError('Data kompetisi belum dapat dimuat. Silakan coba kembali.'))
      .finally(() => setLoading(false));
  }
  useEffect(() => { document.title = 'SmartFootball | Setiap laga punya cerita'; load(); }, []);
  const upcoming = data.fixtures.filter(match => match.status === 'scheduled');
  const matches = upcoming.length ? upcoming.slice(0, 3) : [...data.fixtures].filter(match => match.status === 'completed').reverse().slice(0, 3);
  const featured = upcoming[0];
  const metrics = [[Shield, 'Tim terdaftar', data.counts?.total_teams], [Users, 'Pemain', data.counts?.total_players], [CalendarDays, 'Pertandingan', data.counts?.total_fixtures], [Goal, 'Gol tercipta', data.counts?.total_goals]];
  return <div className="public-home">
    <section className="home-hero"><div className="home-hero-copy"><span className="hero-kicker"><span /> RUMAH BAGI CERITA SEPAK BOLA</span><h1>Lebih dari laga.<br />Ini tentang <em>cerita.</em></h1><p>Dari peluit pertama sampai gol penentu. Ikuti perjalanan tim, kenali para pemain, dan lihat angka di balik setiap pertandingan.</p><div className="hero-actions"><Link className="hero-primary" to="/fixtures">Jelajahi pertandingan <ArrowUpRight size={19} /></Link><Link className="hero-secondary" to="/league-table">Lihat klasemen <ArrowRight size={17} /></Link></div><div className="hero-caption"><span className="hero-caption-line" /> Tim. Talenta. Statistik. Satu lapangan.</div></div>
      <div className="hero-visual"><div className="pitch-glow" /><div className="hero-pitch" aria-hidden="true"><svg viewBox="0 0 360 460" fill="none"><rect x="20" y="20" width="320" height="420" rx="4" /><path d="M20 230h320" /><circle cx="180" cy="230" r="52" /><circle cx="180" cy="230" r="3" fill="currentColor" /><path d="M90 20v74h180V20M135 20v30h90V20M90 440v-74h180v74M135 440v-30h90v30" /><circle cx="180" cy="70" r="3" fill="currentColor" /><circle cx="180" cy="390" r="3" fill="currentColor" /></svg><span className="pitch-player p-one">9</span><span className="pitch-player p-two">7</span><span className="pitch-player p-three">10</span><span className="pitch-player p-four">4</span><span className="pitch-player p-five">1</span></div><div className="hero-visual-label"><Trophy size={16} /> THE BEAUTIFUL GAME</div><div className="hero-match-card"><span className="public-eyebrow">{featured ? 'PERTANDINGAN BERIKUTNYA' : 'KOMPETISI SMARTFOOTBALL'}</span>{featured ? <><div className="hero-match-teams"><ClubMark team={featured.home_team} /><strong>{featured.home_team?.name}</strong><span>vs</span><strong>{featured.away_team?.name}</strong><ClubMark team={featured.away_team} /></div><small>{formatDate(featured.match_date)} · {featured.venue || 'Venue belum ditentukan'}</small></> : <><strong>Lapangan siap. Cerita menanti.</strong><small>{loading ? 'Memuat jadwal kompetisi...' : error ? 'Jadwal belum dapat dimuat.' : 'Jadwal pertandingan akan tampil di sini.'}</small></>}<Link to="/fixtures" aria-label="Lihat jadwal pertandingan"><ArrowUpRight size={18} /></Link></div></div>
    </section>
    <div className="home-body"><section className="home-metrics" aria-label="Ringkasan kompetisi">{metrics.map(([Icon, label, value]) => <div key={label}><Icon size={21} /><div><strong>{loading || error ? '—' : value ?? 0}</strong><span>{label}</span></div></div>)}</section>
      {error && <div className="home-error" role="alert"><span>{error}</span><button onClick={() => { setLoading(true); setError(''); load(); }}><RefreshCw size={15} /> Coba lagi</button></div>}
      {loading ? <div className="home-loading" role="status"><span className="home-spinner" /> Menyiapkan cerita kompetisi...</div> : !error && <>
      <section className="home-competition-grid"><div><SectionHeading eyebrow="MATCH CENTER" title={upcoming.length ? 'Laga yang dinanti.' : 'Dari lapangan.'} to="/fixtures" label="Semua pertandingan" /><div className="home-match-list">{matches.length ? matches.map(match => <Link to="/fixtures" className="home-match-row" key={match.id}><div className="home-match-date"><CalendarDays size={15} /><span>{formatDate(match.match_date)}</span></div><div className="home-match-clubs"><ClubMark team={match.home_team} /><strong>{match.home_team?.name}</strong><span className="match-score">{match.status === 'completed' ? `${match.home_score} : ${match.away_score}` : 'VS'}</span><strong>{match.away_team?.name}</strong><ClubMark team={match.away_team} /></div><span className="home-match-status">{match.status === 'completed' ? 'Selesai' : 'Terjadwal'}</span></Link>) : <div className="home-empty"><CalendarDays size={32} /><h3>Peluit pertama belum berbunyi.</h3><p>Jadwal dan hasil pertandingan akan hadir di sini.</p></div>}</div></div>
      <div><SectionHeading eyebrow="LEAGUE TABLE" title="Peta persaingan." to="/league-table" label="Klasemen" /><div className="home-standings"><div className="home-standing-label"><span>Klub</span><span>Main / Poin</span></div>{data.standings.length ? data.standings.slice(0,4).map((row,index) => <Link className="home-standing-row" to={`/teams/${row.team.id}`} key={row.team.id}><span className="standing-rank">{String(index+1).padStart(2,'0')}</span><ClubMark team={row.team} /><strong>{row.team.name}</strong><span>{row.played}</span><b>{row.points}</b></Link>) : <div className="home-empty"><Trophy size={28} /><p>Tim terdaftar akan muncul di klasemen.</p></div>}</div></div></section>
      <section><SectionHeading eyebrow="PEOPLE OF THE GAME" title="Nama di balik angka." to="/leaderboard" label="Lihat leaderboard" /><div className="home-leaders">{[[Goal,'Pencetak gol',data.leaders.top_scorers,'total_goals','gol'],[Star,'Rating tertinggi',data.leaders.top_rated,'overall_rating','rating']].map(([Icon,title,rows,key,unit]) => <div className="home-leader-card" key={title}><h3><Icon size={19} />{title}</h3>{rows.length ? rows.slice(0,3).map((row,index) => { const player = row.player || row; return <Link to={`/players/${player.id}`} className="home-leader-row" key={player.id}><span className="standing-rank">{String(index+1).padStart(2,'0')}</span><div className="home-player-avatar">{player.photo ? <img src={player.photo} alt="" /> : <Users size={20} />}</div><div><strong>{player.name}</strong><small>{row.team?.name || player.team?.name || '—'}</small></div><b>{unit === 'rating' ? Number(row[key]).toFixed(2) : row[key]}<small>{unit}</small></b></Link>; }) : <div className="home-empty"><p>Performa pemain akan tercatat setelah statistik tersedia.</p></div>}</div>)}</div></section>
      </>}
      <section className="home-explore"><div><span className="public-eyebrow">TEMUKAN SISI LAIN PERMAINAN</span><h2>Kenali klubnya.<br />Temukan talentanya.</h2><p>Setiap tim punya identitas. Setiap pemain punya perjalanan. Mulai jelajahi mereka.</p></div><div className="home-explore-links"><Link to="/teams"><Shield size={25} /><div><strong>Klub & tim</strong><small>Identitas, skuad, dan perjalanan tim.</small></div><ArrowUpRight size={22} /></Link><Link to="/players"><Users size={25} /><div><strong>Profil pemain</strong><small>Posisi, statistik, dan performa individu.</small></div><ArrowUpRight size={22} /></Link></div></section>
    </div>
  </div>;
}

